"""add users roles

Revision ID: 8e6b38ebd287
Revises: 489140672425
Create Date: 2023-05-22 13:57:48.570148

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e6b38ebd287'
down_revision = '489140672425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users',
                  sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default="user"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
